# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course_service_unary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'course_service_unary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ourse_service_unary.proto\"1\n\x06\x43SUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"F\n\x0c\x43SCourseUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x15\n\x04user\x18\x03 \x01(\x0b\x32\x07.CSUser\"\x1f\n\x08\x43SStatus\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\x66\n\rCourseService\x12(\n\nadd_course\x12\r.CSCourseUser\x1a\t.CSStatus\"\x00\x12+\n\rremove_course\x12\r.CSCourseUser\x1a\t.CSStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_service_unary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSUSER']._serialized_start=30
  _globals['_CSUSER']._serialized_end=79
  _globals['_CSCOURSEUSER']._serialized_start=81
  _globals['_CSCOURSEUSER']._serialized_end=151
  _globals['_CSSTATUS']._serialized_start=153
  _globals['_CSSTATUS']._serialized_end=184
  _globals['_COURSESERVICE']._serialized_start=186
  _globals['_COURSESERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
