# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery_service_unary.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'delivery_service_unary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x64\x65livery_service_unary.proto\"1\n\x06\x44SUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"F\n\x0c\x44SCourseUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ourse_name\x18\x02 \x01(\t\x12\x15\n\x04user\x18\x03 \x01(\x0b\x32\x07.DSUser\"\x1f\n\x08\x44SStatus\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32o\n\x0f\x44\x65liveryService\x12,\n\x0e\x64\x65liver_course\x12\r.DSCourseUser\x1a\t.DSStatus\"\x00\x12.\n\x10undeliver_course\x12\r.DSCourseUser\x1a\t.DSStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_service_unary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DSUSER']._serialized_start=32
  _globals['_DSUSER']._serialized_end=81
  _globals['_DSCOURSEUSER']._serialized_start=83
  _globals['_DSCOURSEUSER']._serialized_end=153
  _globals['_DSSTATUS']._serialized_start=155
  _globals['_DSSTATUS']._serialized_end=186
  _globals['_DELIVERYSERVICE']._serialized_start=188
  _globals['_DELIVERYSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
