# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import delivery_service_unary_pb2 as delivery__service__unary__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in delivery_service_unary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeliveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.deliver_course = channel.unary_unary(
                '/DeliveryService/deliver_course',
                request_serializer=delivery__service__unary__pb2.DSCourseUser.SerializeToString,
                response_deserializer=delivery__service__unary__pb2.DSStatus.FromString,
                _registered_method=True)
        self.undeliver_course = channel.unary_unary(
                '/DeliveryService/undeliver_course',
                request_serializer=delivery__service__unary__pb2.DSCourseUser.SerializeToString,
                response_deserializer=delivery__service__unary__pb2.DSStatus.FromString,
                _registered_method=True)


class DeliveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def deliver_course(self, request, context):
        """unary service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def undeliver_course(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeliveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'deliver_course': grpc.unary_unary_rpc_method_handler(
                    servicer.deliver_course,
                    request_deserializer=delivery__service__unary__pb2.DSCourseUser.FromString,
                    response_serializer=delivery__service__unary__pb2.DSStatus.SerializeToString,
            ),
            'undeliver_course': grpc.unary_unary_rpc_method_handler(
                    servicer.undeliver_course,
                    request_deserializer=delivery__service__unary__pb2.DSCourseUser.FromString,
                    response_serializer=delivery__service__unary__pb2.DSStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeliveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DeliveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeliveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def deliver_course(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeliveryService/deliver_course',
            delivery__service__unary__pb2.DSCourseUser.SerializeToString,
            delivery__service__unary__pb2.DSStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def undeliver_course(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeliveryService/undeliver_course',
            delivery__service__unary__pb2.DSCourseUser.SerializeToString,
            delivery__service__unary__pb2.DSStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
